AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  WorkerRoleArn:
    Type: String
    Description: the ARN of the assigned IAM role

Resources:
  Task:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.handler
      Runtime: python3.7
      Tracing: Active
      CodeUri: src/
      Role: !Ref WorkerRoleArn
