AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  WorkerRoleArn:
    Type: String
    Description: the ARN of the assigned IAM role
  NeptuneSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A collection of Security Group IDs capable of interacting with the Neptune Cluster
  NeptuneSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: A collection of Subnet IDs which can interact with the Neptune Cluster

Resources:
  Task:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.handler
      Runtime: python3.7
      Tracing: Active
      CodeUri: src/
      Role: !Ref WorkerRoleArn
  VpcTask:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth.handler
      Runtime: python3.7
      Tracing: Active
      CodeUri: src/
      Role: !Ref WorkerRoleArn
      VpcConfig:
        SecurityGroupIds: !Ref NeptuneSecurityGroupIds
        SubnetIds: !Ref NeptuneSubnetIds
